[package]
name = "nofar-ffi"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "lib"]
name = "nofar_ffi"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
nofar-core = { path = "../nofar-core" }
thiserror.workspace = true
uniffi = { workspace = true, features = ["cli"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "warn"
