package com.nofar.core.data.prepare

import com.nofar.core.model.DemTileId
import com.nofar.core.model.GeoEntity
import com.nofar.core.model.GeoEntityType
import com.nofar.core.model.OsmType
import java.time.Instant
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class CoverageNameResolverTest {
    @Test
    fun isUserProvidedName_rejectsBlankAndAutoGenerated() {
        assertFalse(RegionNamePolicy.isUserProvidedName(""))
        assertFalse(RegionNamePolicy.isUserProvidedName("Area near 32.00, 35.00"))
        assertFalse(RegionNamePolicy.isUserProvidedName("  Region near -32.10, 35.20  "))
        assertFalse(RegionNamePolicy.isUserProvidedName("Downloaded maps"))
    }

    @Test
    fun isUserProvidedName_acceptsCustomNames() {
        assertTrue(RegionNamePolicy.isUserProvidedName("Mount Carmel"))
        assertTrue(RegionNamePolicy.isUserProvidedName("Region near my cabin"))
    }

    @Test
    fun closestEntityName_picksNearestPlaceToReference() {
        val far =
            sampleEntity(
                id = "far",
                name = "Far Village",
                type = GeoEntityType.VILLAGE,
                lat = 32.3,
                lon = 35.3
            )
        val near =
            sampleEntity(
                id = "near",
                name = "Near Town",
                type = GeoEntityType.TOWN,
                lat = 32.01,
                lon = 35.01
            )
        assertEquals(
            "Near Town",
            CoverageNameResolver.closestEntityName(listOf(near, far), referenceLat = 32.0, referenceLon = 35.0)
        )
    }

    @Test
    fun closestEntityName_ignoresPeaksAndBlankNames() {
        val peak = sampleEntity(id = "peak", name = "Some Peak", type = GeoEntityType.PEAK, lat = 32.0, lon = 35.0)
        val blank = sampleEntity(id = "blank", name = "   ", type = GeoEntityType.CITY, lat = 32.0, lon = 35.0)
        val named =
            sampleEntity(id = "named", name = "Haifa", type = GeoEntityType.CITY, lat = 32.05, lon = 35.05)
        assertEquals(
            "Haifa",
            CoverageNameResolver.closestEntityName(listOf(peak, blank, named), referenceLat = 32.0, referenceLon = 35.0)
        )
    }

    @Test
    fun closestEntityName_fallsBackWhenNoPlaces() {
        val blank = sampleEntity(id = "blank", name = "", type = GeoEntityType.CITY, lat = 32.0, lon = 35.0)
        val peak = sampleEntity(id = "peak", name = "Peak", type = GeoEntityType.PEAK, lat = 32.0, lon = 35.0)
        assertEquals(
            "Downloaded maps",
            CoverageNameResolver.closestEntityName(listOf(blank, peak), referenceLat = 32.0, referenceLon = 35.0)
        )
        assertEquals(
            "Downloaded maps",
            CoverageNameResolver.closestEntityName(emptyList(), referenceLat = 32.0, referenceLon = 35.0)
        )
    }

    @Test
    fun referenceCenterFromCellIds_averagesCellCentroids() {
        val cellIds =
            listOf(
                DemTileId.fromCoordinates(32, 35),
                DemTileId.fromCoordinates(32, 36)
            )
        val (lat, lon) = CoverageNameResolver.referenceCenterFromCellIds(cellIds)
        assertEquals(32.5, lat, 0.001)
        assertEquals(36.0, lon, 0.001)
    }

    private fun sampleEntity(
        id: String,
        name: String,
        lat: Double,
        lon: Double,
        type: GeoEntityType = GeoEntityType.PEAK
    ): GeoEntity {
        val now = Instant.now()
        return GeoEntity(
            id = id,
            osmType = OsmType.NODE,
            name = name,
            type = type,
            lat = lat,
            lon = lon,
            elevation = null,
            elevationSource = null,
            lastSeenAt = now
        )
    }
}
