package com.nofar.core.data.prepare

import com.nofar.core.model.DownloadStatus
import com.nofar.core.model.GeoEntity
import com.nofar.core.model.GeoEntityType
import com.nofar.core.model.OsmType
import com.nofar.core.model.Region
import com.nofar.core.model.RegionBounds
import java.time.Instant
import java.util.UUID
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class RegionNameResolverTest {
    @Test
    fun isUserProvidedName_rejectsBlankAndAutoGenerated() {
        assertFalse(RegionNamePolicy.isUserProvidedName(""))
        assertFalse(RegionNamePolicy.isUserProvidedName("Region near 32.00, 35.00"))
        assertFalse(RegionNamePolicy.isUserProvidedName("  Region near -32.10, 35.20  "))
    }

    @Test
    fun isUserProvidedName_acceptsCustomNames() {
        assertTrue(RegionNamePolicy.isUserProvidedName("Mount Carmel"))
        assertTrue(RegionNamePolicy.isUserProvidedName("Region near my cabin"))
    }

    @Test
    fun closestEntityName_picksNearestEntityToRegionCenter() {
        val region = sampleRegion(centerLat = 32.0, centerLon = 35.0)
        val far =
            sampleEntity(
                id = "far",
                name = "Far Peak",
                lat = 32.1,
                lon = 35.1
            )
        val near =
            sampleEntity(
                id = "near",
                name = "Near Town",
                lat = 32.01,
                lon = 35.01
            )
        assertEquals("Near Town", RegionNameResolver.closestEntityName(region, listOf(far, near)))
    }

    @Test
    fun closestEntityName_ignoresBlankNames() {
        val region = sampleRegion(centerLat = 32.0, centerLon = 35.0)
        val blank = sampleEntity(id = "blank", name = "   ", lat = 32.0, lon = 35.0)
        val named = sampleEntity(id = "named", name = "Haifa", lat = 32.05, lon = 35.05)
        assertEquals("Haifa", RegionNameResolver.closestEntityName(region, listOf(blank, named)))
    }

    @Test
    fun closestEntityName_returnsNullWhenNoNamedEntities() {
        val region = sampleRegion(centerLat = 32.0, centerLon = 35.0)
        val blank = sampleEntity(id = "blank", name = "", lat = 32.0, lon = 35.0)
        assertNull(RegionNameResolver.closestEntityName(region, listOf(blank)))
        assertNull(RegionNameResolver.closestEntityName(region, emptyList()))
    }

    private fun sampleRegion(centerLat: Double, centerLon: Double): Region {
        val box = RegionBounds.boundingBox(centerLat, centerLon, 10_000.0)
        val now = Instant.now()
        return Region(
            id = UUID.randomUUID(),
            name = "Region near 32.00, 35.00",
            centerLat = centerLat,
            centerLon = centerLon,
            radiusM = 10_000.0,
            minLat = box.minLat,
            maxLat = box.maxLat,
            minLon = box.minLon,
            maxLon = box.maxLon,
            createdAt = now,
            updatedAt = now,
            downloadStatus = DownloadStatus.DOWNLOADING,
            downloadProgressPct = 40,
            osmDatasetVersion = now,
            estimatedSizeBytes = 0,
            entityCount = 2
        )
    }

    private fun sampleEntity(id: String, name: String, lat: Double, lon: Double): GeoEntity {
        val now = Instant.now()
        return GeoEntity(
            id = id,
            osmType = OsmType.NODE,
            name = name,
            type = GeoEntityType.PEAK,
            lat = lat,
            lon = lon,
            elevation = null,
            elevationSource = null,
            lastSeenAt = now
        )
    }
}
