config:
  validation: true

processors:
  active: true

console-reports:
  active: true

comments:
  active: false

complexity:
  active: true

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true

naming:
  active: true
  FunctionNaming:
    ignoreAnnotated:
      - Composable

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120
